trigger:
- master

variables:
  hugo.version: v0.68.3

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/${{ variables.hugo.version }}/hugo_extended_${{ variables.hugo.version }}_Linux-64bit.deb
  displayName: 'Download Hugo ${{ variables.hugo.version }}'

- script: sudo dpkg -i hugo.deb
  displayName: 'Install Hugo ${{ variables.hugo.version }}'

- script: hugo
  displayName: 'Build Hugo site'

- script: hugo deploy
  displayName: 'Deploy Hugo site'
  env:
    AZURE_STORAGE_ACCOUNT: $(AZURE_STORAGE_ACCOUNT)
    AZURE_STORAGE_KEY: $(AZURE_STORAGE_KEY)
