trigger:
- master

variables:
  hugo_version: '0.68.3'
  root_dir: 'website'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v$(hugo_version)/hugo_extended_$(hugo_version)_Linux-64bit.deb
  displayName: 'Download Hugo $(hugo_version)'

- script: sudo dpkg -i hugo.deb
  displayName: 'Install Hugo $(hugo_version)'

- script: hugo
  displayName: 'Build Hugo site'
  workingDirectory: $(root_dir)

- script: hugo deploy
  displayName: 'Deploy Hugo site'
  workingDirectory: $(root_dir)
  env:
    AZURE_STORAGE_ACCOUNT: $(AZURE_STORAGE_ACCOUNT)
    AZURE_STORAGE_KEY: $(AZURE_STORAGE_KEY)
