trigger:
- master

variables:
  hugo_version: v0.68.3

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/$(hugo_version)/hugo_extended_$(hugo_version)_Linux-64bit.deb
  displayName: 'Download Hugo $(hugo_version)'

- script: sudo dpkg -i hugo.deb
  displayName: 'Install Hugo $(hugo_version)'

- script: hugo
  displayName: 'Build Hugo site'

- script: hugo deploy
  displayName: 'Deploy Hugo site'
  env:
    AZURE_STORAGE_ACCOUNT: $(AZURE_STORAGE_ACCOUNT)
    AZURE_STORAGE_KEY: $(AZURE_STORAGE_KEY)
